query AllPageSlugs($preview: Boolean = false) {
  pageCollection(limit: 100, preview: $preview) {
    items {
      slug
      category
    }
  }
}

fragment PageContentLinks on PageContentLinks {
  entries {
    block {
      sys {
        id
      }
      ... on Section {
        __typename
        sys {
          id
        }
      }
      ... on Skill {
        __typename
        sys {
          id
        }
      }
      ... on SellingPoint {
        __typename
        sys {
          id
        }
      }
    }
  }
  assets {
    block {
      sys {
        id
      }
      url
      description
    }
  }
}

query PageContentBySlug($slug: String, $preview: Boolean = false) {
  pageCollection(preview: $preview, where: { slug: $slug }, limit: 1) {
    items {
      ...PageHeader
      slug
      metaTitle
      content {
        json
        links {
          ...PageContentLinks
        }
      }
    }
  }
}
