fragment Page on Page {
  title
  slug
}

fragment Section on Section {
  breakpoint
  columns
  featured
  fullWidth
  gap
  layout
  margin
  title
  contentCollection(limit: 100) {
    items {
      ... on Feedback {
        ...Feedback
      }
      ... on Skill {
        ...Skill
      }
      ... on SellingPoint {
        ...SellingPoint
      }
      ... on Page {
        ...Page
      }
    }
  }
}

query SectionContent($preview: Boolean = false, $id: String!) {
  section: sectionCollection(
    limit: 1
    where: { sys: { id: $id } }
    preview: $preview
  ) {
    items {
      ...Section
    }
  }
}
