import { Inter } from "next/font/google";
import { draftMode } from "next/headers";
import { type ReactNode } from "react";
import { Wrapper, Main } from "./styles";
import { getClient, ApolloWrapper } from "@/lib/apollo/client";
import { ThemeToggleProvider, StitchesRegistry } from "@/lib/stitches";
import { DraftMode } from "@/components/molecules";
import { Footer, Header } from "@/components/organisms";
import { IconDefs, ConditionalWrapper } from "@/components/atoms";
import { GetLayoutDocument, type SocialItem } from "@/graphql";
import { APOLLO_CLIENTS } from "@/constants";
import type { CategoryType } from "@/types";
import { buildNavigation } from "@/helpers";

const inter = Inter({ subsets: ["latin"] });
const { query } = getClient();
const { CMS } = APOLLO_CLIENTS;

export const revalidate = 5;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const { isEnabled } = draftMode();

  const { data } = await query({
    context: { clientName: CMS },
    query: GetLayoutDocument,
    fetchPolicy: "cache-first",
  });

  const social = data.socialItemCollection?.items as SocialItem[];
  const navigation = buildNavigation(
    data.postCategoryCollection?.items as CategoryType[], // TODO: Should use type from graphql
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <StitchesRegistry>
            <ThemeToggleProvider>
              <IconDefs />
              <ConditionalWrapper
                if={isEnabled}
                wrapWith={children => <DraftMode>{children}</DraftMode>}>
                <Wrapper>
                  <Header navigation={navigation} social={social} />
                  <Main>{children}</Main>
                  <Footer />
                </Wrapper>
              </ConditionalWrapper>
            </ThemeToggleProvider>
          </StitchesRegistry>
        </ApolloWrapper>
      </body>
    </html>
  );
}
