fragment PageHeader on Page {
  title
  kicker
  description
  date
  to
  category
  image {
    url
    description
  }
  agency {
    logo {
      title
      url
    }
    name
    url
  }
  skills: skillsCollection {
    items {
      title
    }
  }

  links: linksCollection {
    items {
      label
      icon
      page {
        slug
      }
      section {
        sys {
          id
        }
      }
    }
  }
}

query PageHeaderBySlug($slug: String, $preview: Boolean = false) {
  pageCollection(preview: $preview, where: { slug: $slug }, limit: 1) {
    items {
      ...PageHeader
    }
  }
}
